export { default as SplashScreen } from './splash.screen'
export { default as LoginScreen } from './login.screen'
export { default as AppScreen } from './app.screen'
export { default as GoalScreen } from './goal.screen'
export { default as StatsScreen } from './stats.screen'
